### ISSUE TITLE
library does not compile in ubuntu 16.04

### ISSUE THREAD

**Issue by federicohyo** [VLOGroup/imageutilities#1]
Hi,

I just downloaded the library from the tag 2.1.
I have the following error while compiling it: 

federico@zfractal:/media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/build$ make
Scanning dependencies of target iugui_automoc
[  1%] Automatic moc for target iugui
Generating moc_qt5disparitymapgpuwidget.cpp
Generating moc_qt5imagegpuwidget.cpp
[  1%] Built target iugui_automoc
[  3%] Building NVCC (Device) object src/CMakeFiles/iugui.dir/iugui/iugui_generated_qt5disparitymapgpuwidget.cu.o
[  4%] Building NVCC (Device) object src/CMakeFiles/iugui.dir/iugui/iugui_generated_qt5imagegpuwidget.cu.o
Scanning dependencies of target iugui
[  6%] Building CXX object src/CMakeFiles/iugui.dir/iugui/qt5imagegpuwidget.cpp.o
In file included from /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.cpp:1:0:
/media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.h:20:1: error: expected class-name before ‘{’ token
 {
 ^
In file included from /usr/include/GL/gl.h:2055:0,
                 from /usr/include/GL/glu.h:38,
                 from /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.cpp:2:
/usr/local/cuda-7.5/samples/common/inc/GL/glext.h:6815:100: error: conflicting declaration ‘typedef void (* PFNGLGETQUERYOBJECTI64VEXTPROC)(GLuint, GLenum, GLint64EXT*)’
 typedef void (APIENTRYP PFNGLGETQUERYOBJECTI64VEXTPROC)(GLuint id, GLenum pname, GLint64EXT *params);
                                                                                                    ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qopengl.h:110:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qopenglwidget.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QOpenGLWidget:1,
                 from /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.h:3,
                 from /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtGui/qopengles2ext.h:846:28: note: previous declaration as ‘typedef void (* PFNGLGETQUERYOBJECTI64VEXTPROC)(GLuint, GLenum, GLint64*)’
 typedef void (GL_APIENTRYP PFNGLGETQUERYOBJECTI64VEXTPROC) (GLuint id, GLenum pname, GLint64 *params);
                            ^
In file included from /usr/include/GL/gl.h:2055:0,
                 from /usr/include/GL/glu.h:38,
                 from /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.cpp:2:
/usr/local/cuda-7.5/samples/common/inc/GL/glext.h:6816:102: error: conflicting declaration ‘typedef void (* PFNGLGETQUERYOBJECTUI64VEXTPROC)(GLuint, GLenum, GLuint64EXT*)’
 typedef void (APIENTRYP PFNGLGETQUERYOBJECTUI64VEXTPROC)(GLuint id, GLenum pname, GLuint64EXT *params);
                                                                                                      ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qopengl.h:110:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qopenglwidget.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QOpenGLWidget:1,
                 from /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.h:3,
                 from /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtGui/qopengles2ext.h:847:28: note: previous declaration as ‘typedef void (* PFNGLGETQUERYOBJECTUI64VEXTPROC)(GLuint, GLenum, GLuint64*)’
 typedef void (GL_APIENTRYP PFNGLGETQUERYOBJECTUI64VEXTPROC) (GLuint id, GLenum pname, GLuint64 *params);
                            ^
/media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.cpp: In member function ‘virtual void iu::Qt5ImageGpuWidget::initializeGL()’:
/media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/3rdparty/dvs-reconstruction/imageutilities-2.1/src/iugui/qt5imagegpuwidget.cpp:169:31: error: ‘initializeOpenGLFunctions’ was not declared in this scope
     initializeOpenGLFunctions();   // initialize the QOpenGLFunctions_x_x
                               ^
src/CMakeFiles/iugui.dir/build.make:76: recipe for target 'src/CMakeFiles/iugui.dir/iugui/qt5imagegpuwidget.cpp.o' failed
make[2]: *** [src/CMakeFiles/iugui.dir/iugui/qt5imagegpuwidget.cpp.o] Error 1
CMakeFiles/Makefile2:98: recipe for target 'src/CMakeFiles/iugui.dir/all' failed
make[1]: *** [src/CMakeFiles/iugui.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

any ideas?
I look forward to your help.

with best regards,
 Federico

**Comment by reini1305** [comment]
I have no 16.04 machine yet, but for 14.04 I had to install Qt 5.6 by hand because the included version was too old (and something with OpenGL was broken).

**Comment by reini1305** [comment]
I'll try to reproduce the error using a fresh installation of 16.04 in a VM.

**Comment by reini1305** [comment]
I just downloaded a fresh copy of Ubuntu 16.04 from osboxes.org (64-bit). There I installed the following things using apt:
- cuda-toolkit-8-0
- libopencv-dev
- libqt5widgets5
- libqt5opengl5-dev

I could not reproduce your above error, the library compiled fine (including `iugui`and `iuio`). You mentioned the tag 2.1, maybe try a checkout from `master`?

**Comment by reini1305** [comment]
Did you make any progress on this?

**Comment by federicohyo** [comment]
Hi, 
yes I have been able to compile imageutilities. 
I had to update cuda toolkit from 7.5 to 8.

thank you a lot for your support.
